# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg/CMakeFiles /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg/CMakeFiles /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/google/home/hasinoff/sjpeg_optimize/sjpeg/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sjpeg

# Build rule for target.
sjpeg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sjpeg
.PHONY : sjpeg

# fast build rule for target.
sjpeg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/build
.PHONY : sjpeg/fast

#=============================================================================
# Target rules for targets named sjpeg-utils

# Build rule for target.
sjpeg-utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sjpeg-utils
.PHONY : sjpeg-utils

# fast build rule for target.
sjpeg-utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-utils.dir/build.make CMakeFiles/sjpeg-utils.dir/build
.PHONY : sjpeg-utils/fast

#=============================================================================
# Target rules for targets named sjpeg-bin

# Build rule for target.
sjpeg-bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sjpeg-bin
.PHONY : sjpeg-bin

# fast build rule for target.
sjpeg-bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-bin.dir/build.make CMakeFiles/sjpeg-bin.dir/build
.PHONY : sjpeg-bin/fast

#=============================================================================
# Target rules for targets named vjpeg

# Build rule for target.
vjpeg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vjpeg
.PHONY : vjpeg

# fast build rule for target.
vjpeg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vjpeg.dir/build.make CMakeFiles/vjpeg.dir/build
.PHONY : vjpeg/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

examples/sjpeg.o: examples/sjpeg.cc.o
.PHONY : examples/sjpeg.o

# target to build an object file
examples/sjpeg.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-bin.dir/build.make CMakeFiles/sjpeg-bin.dir/examples/sjpeg.cc.o
.PHONY : examples/sjpeg.cc.o

examples/sjpeg.i: examples/sjpeg.cc.i
.PHONY : examples/sjpeg.i

# target to preprocess a source file
examples/sjpeg.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-bin.dir/build.make CMakeFiles/sjpeg-bin.dir/examples/sjpeg.cc.i
.PHONY : examples/sjpeg.cc.i

examples/sjpeg.s: examples/sjpeg.cc.s
.PHONY : examples/sjpeg.s

# target to generate assembly for a file
examples/sjpeg.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-bin.dir/build.make CMakeFiles/sjpeg-bin.dir/examples/sjpeg.cc.s
.PHONY : examples/sjpeg.cc.s

examples/utils.o: examples/utils.cc.o
.PHONY : examples/utils.o

# target to build an object file
examples/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-utils.dir/build.make CMakeFiles/sjpeg-utils.dir/examples/utils.cc.o
.PHONY : examples/utils.cc.o

examples/utils.i: examples/utils.cc.i
.PHONY : examples/utils.i

# target to preprocess a source file
examples/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-utils.dir/build.make CMakeFiles/sjpeg-utils.dir/examples/utils.cc.i
.PHONY : examples/utils.cc.i

examples/utils.s: examples/utils.cc.s
.PHONY : examples/utils.s

# target to generate assembly for a file
examples/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg-utils.dir/build.make CMakeFiles/sjpeg-utils.dir/examples/utils.cc.s
.PHONY : examples/utils.cc.s

examples/vjpeg.o: examples/vjpeg.cc.o
.PHONY : examples/vjpeg.o

# target to build an object file
examples/vjpeg.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vjpeg.dir/build.make CMakeFiles/vjpeg.dir/examples/vjpeg.cc.o
.PHONY : examples/vjpeg.cc.o

examples/vjpeg.i: examples/vjpeg.cc.i
.PHONY : examples/vjpeg.i

# target to preprocess a source file
examples/vjpeg.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vjpeg.dir/build.make CMakeFiles/vjpeg.dir/examples/vjpeg.cc.i
.PHONY : examples/vjpeg.cc.i

examples/vjpeg.s: examples/vjpeg.cc.s
.PHONY : examples/vjpeg.s

# target to generate assembly for a file
examples/vjpeg.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vjpeg.dir/build.make CMakeFiles/vjpeg.dir/examples/vjpeg.cc.s
.PHONY : examples/vjpeg.cc.s

src/api.o: src/api.cc.o
.PHONY : src/api.o

# target to build an object file
src/api.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/api.cc.o
.PHONY : src/api.cc.o

src/api.i: src/api.cc.i
.PHONY : src/api.i

# target to preprocess a source file
src/api.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/api.cc.i
.PHONY : src/api.cc.i

src/api.s: src/api.cc.s
.PHONY : src/api.s

# target to generate assembly for a file
src/api.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/api.cc.s
.PHONY : src/api.cc.s

src/bit_writer.o: src/bit_writer.cc.o
.PHONY : src/bit_writer.o

# target to build an object file
src/bit_writer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/bit_writer.cc.o
.PHONY : src/bit_writer.cc.o

src/bit_writer.i: src/bit_writer.cc.i
.PHONY : src/bit_writer.i

# target to preprocess a source file
src/bit_writer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/bit_writer.cc.i
.PHONY : src/bit_writer.cc.i

src/bit_writer.s: src/bit_writer.cc.s
.PHONY : src/bit_writer.s

# target to generate assembly for a file
src/bit_writer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/bit_writer.cc.s
.PHONY : src/bit_writer.cc.s

src/colors_rgb.o: src/colors_rgb.cc.o
.PHONY : src/colors_rgb.o

# target to build an object file
src/colors_rgb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/colors_rgb.cc.o
.PHONY : src/colors_rgb.cc.o

src/colors_rgb.i: src/colors_rgb.cc.i
.PHONY : src/colors_rgb.i

# target to preprocess a source file
src/colors_rgb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/colors_rgb.cc.i
.PHONY : src/colors_rgb.cc.i

src/colors_rgb.s: src/colors_rgb.cc.s
.PHONY : src/colors_rgb.s

# target to generate assembly for a file
src/colors_rgb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/colors_rgb.cc.s
.PHONY : src/colors_rgb.cc.s

src/dichotomy.o: src/dichotomy.cc.o
.PHONY : src/dichotomy.o

# target to build an object file
src/dichotomy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/dichotomy.cc.o
.PHONY : src/dichotomy.cc.o

src/dichotomy.i: src/dichotomy.cc.i
.PHONY : src/dichotomy.i

# target to preprocess a source file
src/dichotomy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/dichotomy.cc.i
.PHONY : src/dichotomy.cc.i

src/dichotomy.s: src/dichotomy.cc.s
.PHONY : src/dichotomy.s

# target to generate assembly for a file
src/dichotomy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/dichotomy.cc.s
.PHONY : src/dichotomy.cc.s

src/enc.o: src/enc.cc.o
.PHONY : src/enc.o

# target to build an object file
src/enc.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc.cc.o
.PHONY : src/enc.cc.o

src/enc.i: src/enc.cc.i
.PHONY : src/enc.i

# target to preprocess a source file
src/enc.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc.cc.i
.PHONY : src/enc.cc.i

src/enc.s: src/enc.cc.s
.PHONY : src/enc.s

# target to generate assembly for a file
src/enc.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc.cc.s
.PHONY : src/enc.cc.s

src/enc_parallel.o: src/enc_parallel.cc.o
.PHONY : src/enc_parallel.o

# target to build an object file
src/enc_parallel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc_parallel.cc.o
.PHONY : src/enc_parallel.cc.o

src/enc_parallel.i: src/enc_parallel.cc.i
.PHONY : src/enc_parallel.i

# target to preprocess a source file
src/enc_parallel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc_parallel.cc.i
.PHONY : src/enc_parallel.cc.i

src/enc_parallel.s: src/enc_parallel.cc.s
.PHONY : src/enc_parallel.s

# target to generate assembly for a file
src/enc_parallel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/enc_parallel.cc.s
.PHONY : src/enc_parallel.cc.s

src/encoders.o: src/encoders.cc.o
.PHONY : src/encoders.o

# target to build an object file
src/encoders.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/encoders.cc.o
.PHONY : src/encoders.cc.o

src/encoders.i: src/encoders.cc.i
.PHONY : src/encoders.i

# target to preprocess a source file
src/encoders.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/encoders.cc.i
.PHONY : src/encoders.cc.i

src/encoders.s: src/encoders.cc.s
.PHONY : src/encoders.s

# target to generate assembly for a file
src/encoders.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/encoders.cc.s
.PHONY : src/encoders.cc.s

src/entropy.o: src/entropy.cc.o
.PHONY : src/entropy.o

# target to build an object file
src/entropy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/entropy.cc.o
.PHONY : src/entropy.cc.o

src/entropy.i: src/entropy.cc.i
.PHONY : src/entropy.i

# target to preprocess a source file
src/entropy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/entropy.cc.i
.PHONY : src/entropy.cc.i

src/entropy.s: src/entropy.cc.s
.PHONY : src/entropy.s

# target to generate assembly for a file
src/entropy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/entropy.cc.s
.PHONY : src/entropy.cc.s

src/fdct.o: src/fdct.cc.o
.PHONY : src/fdct.o

# target to build an object file
src/fdct.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/fdct.cc.o
.PHONY : src/fdct.cc.o

src/fdct.i: src/fdct.cc.i
.PHONY : src/fdct.i

# target to preprocess a source file
src/fdct.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/fdct.cc.i
.PHONY : src/fdct.cc.i

src/fdct.s: src/fdct.cc.s
.PHONY : src/fdct.s

# target to generate assembly for a file
src/fdct.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/fdct.cc.s
.PHONY : src/fdct.cc.s

src/headers.o: src/headers.cc.o
.PHONY : src/headers.o

# target to build an object file
src/headers.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/headers.cc.o
.PHONY : src/headers.cc.o

src/headers.i: src/headers.cc.i
.PHONY : src/headers.i

# target to preprocess a source file
src/headers.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/headers.cc.i
.PHONY : src/headers.cc.i

src/headers.s: src/headers.cc.s
.PHONY : src/headers.s

# target to generate assembly for a file
src/headers.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/headers.cc.s
.PHONY : src/headers.cc.s

src/histogram.o: src/histogram.cc.o
.PHONY : src/histogram.o

# target to build an object file
src/histogram.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/histogram.cc.o
.PHONY : src/histogram.cc.o

src/histogram.i: src/histogram.cc.i
.PHONY : src/histogram.i

# target to preprocess a source file
src/histogram.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/histogram.cc.i
.PHONY : src/histogram.cc.i

src/histogram.s: src/histogram.cc.s
.PHONY : src/histogram.s

# target to generate assembly for a file
src/histogram.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/histogram.cc.s
.PHONY : src/histogram.cc.s

src/jpeg_tools.o: src/jpeg_tools.cc.o
.PHONY : src/jpeg_tools.o

# target to build an object file
src/jpeg_tools.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/jpeg_tools.cc.o
.PHONY : src/jpeg_tools.cc.o

src/jpeg_tools.i: src/jpeg_tools.cc.i
.PHONY : src/jpeg_tools.i

# target to preprocess a source file
src/jpeg_tools.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/jpeg_tools.cc.i
.PHONY : src/jpeg_tools.cc.i

src/jpeg_tools.s: src/jpeg_tools.cc.s
.PHONY : src/jpeg_tools.s

# target to generate assembly for a file
src/jpeg_tools.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/jpeg_tools.cc.s
.PHONY : src/jpeg_tools.cc.s

src/prog.o: src/prog.cc.o
.PHONY : src/prog.o

# target to build an object file
src/prog.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/prog.cc.o
.PHONY : src/prog.cc.o

src/prog.i: src/prog.cc.i
.PHONY : src/prog.i

# target to preprocess a source file
src/prog.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/prog.cc.i
.PHONY : src/prog.cc.i

src/prog.s: src/prog.cc.s
.PHONY : src/prog.s

# target to generate assembly for a file
src/prog.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/prog.cc.s
.PHONY : src/prog.cc.s

src/quantize.o: src/quantize.cc.o
.PHONY : src/quantize.o

# target to build an object file
src/quantize.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/quantize.cc.o
.PHONY : src/quantize.cc.o

src/quantize.i: src/quantize.cc.i
.PHONY : src/quantize.i

# target to preprocess a source file
src/quantize.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/quantize.cc.i
.PHONY : src/quantize.cc.i

src/quantize.s: src/quantize.cc.s
.PHONY : src/quantize.s

# target to generate assembly for a file
src/quantize.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/quantize.cc.s
.PHONY : src/quantize.cc.s

src/score_7.o: src/score_7.cc.o
.PHONY : src/score_7.o

# target to build an object file
src/score_7.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/score_7.cc.o
.PHONY : src/score_7.cc.o

src/score_7.i: src/score_7.cc.i
.PHONY : src/score_7.i

# target to preprocess a source file
src/score_7.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/score_7.cc.i
.PHONY : src/score_7.cc.i

src/score_7.s: src/score_7.cc.s
.PHONY : src/score_7.s

# target to generate assembly for a file
src/score_7.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/score_7.cc.s
.PHONY : src/score_7.cc.s

src/yuv_convert.o: src/yuv_convert.cc.o
.PHONY : src/yuv_convert.o

# target to build an object file
src/yuv_convert.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/yuv_convert.cc.o
.PHONY : src/yuv_convert.cc.o

src/yuv_convert.i: src/yuv_convert.cc.i
.PHONY : src/yuv_convert.i

# target to preprocess a source file
src/yuv_convert.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/yuv_convert.cc.i
.PHONY : src/yuv_convert.cc.i

src/yuv_convert.s: src/yuv_convert.cc.s
.PHONY : src/yuv_convert.s

# target to generate assembly for a file
src/yuv_convert.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sjpeg.dir/build.make CMakeFiles/sjpeg.dir/src/yuv_convert.cc.s
.PHONY : src/yuv_convert.cc.s

tests/unit_test.o: tests/unit_test.cc.o
.PHONY : tests/unit_test.o

# target to build an object file
tests/unit_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/tests/unit_test.cc.o
.PHONY : tests/unit_test.cc.o

tests/unit_test.i: tests/unit_test.cc.i
.PHONY : tests/unit_test.i

# target to preprocess a source file
tests/unit_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/tests/unit_test.cc.i
.PHONY : tests/unit_test.cc.i

tests/unit_test.s: tests/unit_test.cc.s
.PHONY : tests/unit_test.s

# target to generate assembly for a file
tests/unit_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/tests/unit_test.cc.s
.PHONY : tests/unit_test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... check"
	@echo "... sjpeg"
	@echo "... sjpeg-bin"
	@echo "... sjpeg-utils"
	@echo "... unit_test"
	@echo "... vjpeg"
	@echo "... examples/sjpeg.o"
	@echo "... examples/sjpeg.i"
	@echo "... examples/sjpeg.s"
	@echo "... examples/utils.o"
	@echo "... examples/utils.i"
	@echo "... examples/utils.s"
	@echo "... examples/vjpeg.o"
	@echo "... examples/vjpeg.i"
	@echo "... examples/vjpeg.s"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/bit_writer.o"
	@echo "... src/bit_writer.i"
	@echo "... src/bit_writer.s"
	@echo "... src/colors_rgb.o"
	@echo "... src/colors_rgb.i"
	@echo "... src/colors_rgb.s"
	@echo "... src/dichotomy.o"
	@echo "... src/dichotomy.i"
	@echo "... src/dichotomy.s"
	@echo "... src/enc.o"
	@echo "... src/enc.i"
	@echo "... src/enc.s"
	@echo "... src/enc_parallel.o"
	@echo "... src/enc_parallel.i"
	@echo "... src/enc_parallel.s"
	@echo "... src/encoders.o"
	@echo "... src/encoders.i"
	@echo "... src/encoders.s"
	@echo "... src/entropy.o"
	@echo "... src/entropy.i"
	@echo "... src/entropy.s"
	@echo "... src/fdct.o"
	@echo "... src/fdct.i"
	@echo "... src/fdct.s"
	@echo "... src/headers.o"
	@echo "... src/headers.i"
	@echo "... src/headers.s"
	@echo "... src/histogram.o"
	@echo "... src/histogram.i"
	@echo "... src/histogram.s"
	@echo "... src/jpeg_tools.o"
	@echo "... src/jpeg_tools.i"
	@echo "... src/jpeg_tools.s"
	@echo "... src/prog.o"
	@echo "... src/prog.i"
	@echo "... src/prog.s"
	@echo "... src/quantize.o"
	@echo "... src/quantize.i"
	@echo "... src/quantize.s"
	@echo "... src/score_7.o"
	@echo "... src/score_7.i"
	@echo "... src/score_7.s"
	@echo "... src/yuv_convert.o"
	@echo "... src/yuv_convert.i"
	@echo "... src/yuv_convert.s"
	@echo "... tests/unit_test.o"
	@echo "... tests/unit_test.i"
	@echo "... tests/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

